# Generated by Django 2.2.6 on 2019-10-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caliber_pipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Pipe',
        ),
    ]
